# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
    config.vm.box = "debian/bullseye64"
    #config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 3306, host: 13306

    #config.vm.network "private_network", ip: "10.0.0.10", netmask: "255.255.255.0"
    #config.vm.network "private_network", ip: "10.0.0.10"
  
    config.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "2048"
        vb.cpus = "2"
        vb.name = "LAMP"
    end

    config.vm.provision "shell", inline: <<-SHELL
    
        #Instalacion LAMP
        apt update
        apt -y install debconf-utils mariadb-server apache2 php libapache2-mod-php php-xml php-cli php-mysql php-zip php-curl php-xml php-mbstring php-zip php-gd unzip curl

        # #Instalacion docker y docker compose
        # apt install -y docker.io
        # DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
        # mkdir -p $DOCKER_CONFIG/cli-plugins
        # curl -SL https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
        # chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose

        # #Instalacion node
        # wget https://nodejs.org/dist/v20.10.0/node-v20.10.0-linux-x64.tar.xz
        # tar -xvf node*
        # rm -rf node-v20.10.0-linux-x64.tar.xz
        # mv node* /bin/nodejs
        # echo 'PATH=$PATH:/etc/bin/nodejs/bin' >> /etc/bash.bashrc
        # source /etc/bash.bashrc

        # #Creacion usuario mariadb
        mariadb -e "CREATE OR REPLACE USER 'vagrant'@'localhost' IDENTIFIED BY 'vagrant';"
        mariadb -e "GRANT ALL PRIVILEGES ON *.* TO 'vagrant'@'localhost' WITH GRANT OPTION;"

        #Descarga y configuración phpmyadmin
        echo 'phpmyadmin phpmyadmin/password-confirm string abc123.' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/password-confirm string abc123.' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/mysql/app-pass string abc123.' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/mysql/admin-pass string abc123.' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/app-password-confirm string abc123.' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/db/app-user string phpmyadmin@localhost' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/dbconfig-install boolean true' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/missing-db-package-error select abort' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/mysql/method select Unix socket' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/install-error select abort' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/passwords-do-not-match error' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/dbconfig-remove boolean true' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/upgrade-error select abort' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/purge boolean false' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/internal/reconfiguring boolean false' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/db/dbname string phpmyadmin' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/remote/port string' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/upgrade-backup boolean true' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/remote/newhost string' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/dbconfig-upgrade boolean true' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/remote/host  select localhost' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/mysql/admin-user string  root' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/database-type select  mysql' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/remove-error select abort' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/internal/skip-preseed boolean false' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/mysql/authplugin select default' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/dbconfig-reinstall boolean false' | debconf-set-selections -v
        echo 'phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2' | debconf-set-selections -v

        apt install -y phpmyadmin
    SHELL
end
